# Base Image
FROM mysql

# Creating root User and it's password
ENV MYSQL_ROOT_USER="<enter user name>"
ENV MYSQL_ROOT_PASSWORD="<enter your password>"

# The volume is Bind mounted
#ADD first_schema.sql /docker-entrypoint-initdb.d/first_schema.sql



